/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStreamTestRouteImport } from './routes/api/stream-test'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedTeacherEscalationsRouteImport } from './routes/_authenticated/teacher.escalations'
import { Route as AuthenticatedTutorThreadIdRouteImport } from './routes/_authenticated/tutor.$threadId'
import { Route as AuthenticatedTutorChatsRouteImport } from './routes/_authenticated/tutor.chats'
import { Route as AuthenticatedTutorDocumentsRouteImport } from './routes/_authenticated/tutor.documents'
import { Route as AuthenticatedTutorPlannerRouteImport } from './routes/_authenticated/tutor.planner'
import { Route as AuthenticatedTutorQuizzesRouteImport } from './routes/_authenticated/tutor.quizzes'
import { Route as AuthenticatedTutorSavedRouteImport } from './routes/_authenticated/tutor.saved'
import { Route as ApiMpesaCallbackRouteImport } from './routes/api/mpesa/callback'
import { Route as ApiMpesaInitiateRouteImport } from './routes/api/mpesa/initiate'
import { Route as ApiNewsletterSendRouteImport } from './routes/api/newsletter/send'
import { Route as ApiNewsletterSubscribeRouteImport } from './routes/api/newsletter/subscribe'
import { Route as ApiNotificationsDigestRouteImport } from './routes/api/notifications/digest'
import { Route as ApiNotificationsEmailRouteImport } from './routes/api/notifications/email'
import { Route as ApiNotificationsPushSendRouteImport } from './routes/api/notifications/push-send'
import { Route as ApiNotificationsPushSubscribeRouteImport } from './routes/api/notifications/push-subscribe'
import { Route as ApiSettingsEventsRouteImport } from './routes/api/settings/events'
import { Route as ApiTutorThreadsRouteImport } from './routes/api/tutor/threads'
import { Route as AuthenticatedTutorQuizzesQuizIdRouteImport } from './routes/_authenticated/tutor.quizzes_.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamTestRoute = ApiStreamTestRouteImport.update({
  id: '/api/stream-test',
  path: '/api/stream-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherEscalationsRoute =
  AuthenticatedTeacherEscalationsRouteImport.update({
    id: '/teacher/escalations',
    path: '/teacher/escalations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTutorThreadIdRoute =
  AuthenticatedTutorThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedTutorChatsRoute = AuthenticatedTutorChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedTutorRoute,
} as any)
const AuthenticatedTutorDocumentsRoute =
  AuthenticatedTutorDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedTutorPlannerRoute =
  AuthenticatedTutorPlannerRouteImport.update({
    id: '/planner',
    path: '/planner',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedTutorQuizzesRoute =
  AuthenticatedTutorQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedTutorSavedRoute = AuthenticatedTutorSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedTutorRoute,
} as any)
const ApiMpesaCallbackRoute = ApiMpesaCallbackRouteImport.update({
  id: '/api/mpesa/callback',
  path: '/api/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaInitiateRoute = ApiMpesaInitiateRouteImport.update({
  id: '/api/mpesa/initiate',
  path: '/api/mpesa/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterSendRoute = ApiNewsletterSendRouteImport.update({
  id: '/api/newsletter/send',
  path: '/api/newsletter/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterSubscribeRoute = ApiNewsletterSubscribeRouteImport.update({
  id: '/api/newsletter/subscribe',
  path: '/api/newsletter/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsDigestRoute = ApiNotificationsDigestRouteImport.update({
  id: '/api/notifications/digest',
  path: '/api/notifications/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsEmailRoute = ApiNotificationsEmailRouteImport.update({
  id: '/api/notifications/email',
  path: '/api/notifications/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsPushSendRoute =
  ApiNotificationsPushSendRouteImport.update({
    id: '/api/notifications/push-send',
    path: '/api/notifications/push-send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationsPushSubscribeRoute =
  ApiNotificationsPushSubscribeRouteImport.update({
    id: '/api/notifications/push-subscribe',
    path: '/api/notifications/push-subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSettingsEventsRoute = ApiSettingsEventsRouteImport.update({
  id: '/api/settings/events',
  path: '/api/settings/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorThreadsRoute = ApiTutorThreadsRouteImport.update({
  id: '/api/tutor/threads',
  path: '/api/tutor/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorQuizzesQuizIdRoute =
  AuthenticatedTutorQuizzesQuizIdRouteImport.update({
    id: '/quizzes_/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream-test': typeof ApiStreamTestRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/teacher/escalations': typeof AuthenticatedTeacherEscalationsRoute
  '/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/tutor/chats': typeof AuthenticatedTutorChatsRoute
  '/tutor/documents': typeof AuthenticatedTutorDocumentsRoute
  '/tutor/planner': typeof AuthenticatedTutorPlannerRoute
  '/tutor/quizzes': typeof AuthenticatedTutorQuizzesRoute
  '/tutor/saved': typeof AuthenticatedTutorSavedRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa/initiate': typeof ApiMpesaInitiateRoute
  '/api/newsletter/send': typeof ApiNewsletterSendRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/notifications/digest': typeof ApiNotificationsDigestRoute
  '/api/notifications/email': typeof ApiNotificationsEmailRoute
  '/api/notifications/push-send': typeof ApiNotificationsPushSendRoute
  '/api/notifications/push-subscribe': typeof ApiNotificationsPushSubscribeRoute
  '/api/settings/events': typeof ApiSettingsEventsRoute
  '/api/tutor/threads': typeof ApiTutorThreadsRoute
  '/tutor/quizzes/$quizId': typeof AuthenticatedTutorQuizzesQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream-test': typeof ApiStreamTestRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/teacher/escalations': typeof AuthenticatedTeacherEscalationsRoute
  '/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/tutor/chats': typeof AuthenticatedTutorChatsRoute
  '/tutor/documents': typeof AuthenticatedTutorDocumentsRoute
  '/tutor/planner': typeof AuthenticatedTutorPlannerRoute
  '/tutor/quizzes': typeof AuthenticatedTutorQuizzesRoute
  '/tutor/saved': typeof AuthenticatedTutorSavedRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa/initiate': typeof ApiMpesaInitiateRoute
  '/api/newsletter/send': typeof ApiNewsletterSendRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/notifications/digest': typeof ApiNotificationsDigestRoute
  '/api/notifications/email': typeof ApiNotificationsEmailRoute
  '/api/notifications/push-send': typeof ApiNotificationsPushSendRoute
  '/api/notifications/push-subscribe': typeof ApiNotificationsPushSubscribeRoute
  '/api/settings/events': typeof ApiSettingsEventsRoute
  '/api/tutor/threads': typeof ApiTutorThreadsRoute
  '/tutor/quizzes/$quizId': typeof AuthenticatedTutorQuizzesQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream-test': typeof ApiStreamTestRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/teacher/escalations': typeof AuthenticatedTeacherEscalationsRoute
  '/_authenticated/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/_authenticated/tutor/chats': typeof AuthenticatedTutorChatsRoute
  '/_authenticated/tutor/documents': typeof AuthenticatedTutorDocumentsRoute
  '/_authenticated/tutor/planner': typeof AuthenticatedTutorPlannerRoute
  '/_authenticated/tutor/quizzes': typeof AuthenticatedTutorQuizzesRoute
  '/_authenticated/tutor/saved': typeof AuthenticatedTutorSavedRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa/initiate': typeof ApiMpesaInitiateRoute
  '/api/newsletter/send': typeof ApiNewsletterSendRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/notifications/digest': typeof ApiNotificationsDigestRoute
  '/api/notifications/email': typeof ApiNotificationsEmailRoute
  '/api/notifications/push-send': typeof ApiNotificationsPushSendRoute
  '/api/notifications/push-subscribe': typeof ApiNotificationsPushSubscribeRoute
  '/api/settings/events': typeof ApiSettingsEventsRoute
  '/api/tutor/threads': typeof ApiTutorThreadsRoute
  '/_authenticated/tutor/quizzes_/$quizId': typeof AuthenticatedTutorQuizzesQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/callback'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/verify-email'
    | '/settings'
    | '/tutor'
    | '/api/chat'
    | '/api/health'
    | '/api/stream-test'
    | '/admin/users'
    | '/teacher/escalations'
    | '/tutor/$threadId'
    | '/tutor/chats'
    | '/tutor/documents'
    | '/tutor/planner'
    | '/tutor/quizzes'
    | '/tutor/saved'
    | '/api/mpesa/callback'
    | '/api/mpesa/initiate'
    | '/api/newsletter/send'
    | '/api/newsletter/subscribe'
    | '/api/notifications/digest'
    | '/api/notifications/email'
    | '/api/notifications/push-send'
    | '/api/notifications/push-subscribe'
    | '/api/settings/events'
    | '/api/tutor/threads'
    | '/tutor/quizzes/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/callback'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/verify-email'
    | '/settings'
    | '/tutor'
    | '/api/chat'
    | '/api/health'
    | '/api/stream-test'
    | '/admin/users'
    | '/teacher/escalations'
    | '/tutor/$threadId'
    | '/tutor/chats'
    | '/tutor/documents'
    | '/tutor/planner'
    | '/tutor/quizzes'
    | '/tutor/saved'
    | '/api/mpesa/callback'
    | '/api/mpesa/initiate'
    | '/api/newsletter/send'
    | '/api/newsletter/subscribe'
    | '/api/notifications/digest'
    | '/api/notifications/email'
    | '/api/notifications/push-send'
    | '/api/notifications/push-subscribe'
    | '/api/settings/events'
    | '/api/tutor/threads'
    | '/tutor/quizzes/$quizId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/callback'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/settings'
    | '/_authenticated/tutor'
    | '/api/chat'
    | '/api/health'
    | '/api/stream-test'
    | '/_authenticated/admin/users'
    | '/_authenticated/teacher/escalations'
    | '/_authenticated/tutor/$threadId'
    | '/_authenticated/tutor/chats'
    | '/_authenticated/tutor/documents'
    | '/_authenticated/tutor/planner'
    | '/_authenticated/tutor/quizzes'
    | '/_authenticated/tutor/saved'
    | '/api/mpesa/callback'
    | '/api/mpesa/initiate'
    | '/api/newsletter/send'
    | '/api/newsletter/subscribe'
    | '/api/notifications/digest'
    | '/api/notifications/email'
    | '/api/notifications/push-send'
    | '/api/notifications/push-subscribe'
    | '/api/settings/events'
    | '/api/tutor/threads'
    | '/_authenticated/tutor/quizzes_/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CallbackRoute: typeof CallbackRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStreamTestRoute: typeof ApiStreamTestRoute
  ApiMpesaCallbackRoute: typeof ApiMpesaCallbackRoute
  ApiMpesaInitiateRoute: typeof ApiMpesaInitiateRoute
  ApiNewsletterSendRoute: typeof ApiNewsletterSendRoute
  ApiNewsletterSubscribeRoute: typeof ApiNewsletterSubscribeRoute
  ApiNotificationsDigestRoute: typeof ApiNotificationsDigestRoute
  ApiNotificationsEmailRoute: typeof ApiNotificationsEmailRoute
  ApiNotificationsPushSendRoute: typeof ApiNotificationsPushSendRoute
  ApiNotificationsPushSubscribeRoute: typeof ApiNotificationsPushSubscribeRoute
  ApiSettingsEventsRoute: typeof ApiSettingsEventsRoute
  ApiTutorThreadsRoute: typeof ApiTutorThreadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-test': {
      id: '/api/stream-test'
      path: '/api/stream-test'
      fullPath: '/api/stream-test'
      preLoaderRoute: typeof ApiStreamTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/escalations': {
      id: '/_authenticated/teacher/escalations'
      path: '/teacher/escalations'
      fullPath: '/teacher/escalations'
      preLoaderRoute: typeof AuthenticatedTeacherEscalationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tutor/$threadId': {
      id: '/_authenticated/tutor/$threadId'
      path: '/$threadId'
      fullPath: '/tutor/$threadId'
      preLoaderRoute: typeof AuthenticatedTutorThreadIdRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/chats': {
      id: '/_authenticated/tutor/chats'
      path: '/chats'
      fullPath: '/tutor/chats'
      preLoaderRoute: typeof AuthenticatedTutorChatsRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/documents': {
      id: '/_authenticated/tutor/documents'
      path: '/documents'
      fullPath: '/tutor/documents'
      preLoaderRoute: typeof AuthenticatedTutorDocumentsRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/planner': {
      id: '/_authenticated/tutor/planner'
      path: '/planner'
      fullPath: '/tutor/planner'
      preLoaderRoute: typeof AuthenticatedTutorPlannerRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/quizzes': {
      id: '/_authenticated/tutor/quizzes'
      path: '/quizzes'
      fullPath: '/tutor/quizzes'
      preLoaderRoute: typeof AuthenticatedTutorQuizzesRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/saved': {
      id: '/_authenticated/tutor/saved'
      path: '/saved'
      fullPath: '/tutor/saved'
      preLoaderRoute: typeof AuthenticatedTutorSavedRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/api/mpesa/callback': {
      id: '/api/mpesa/callback'
      path: '/api/mpesa/callback'
      fullPath: '/api/mpesa/callback'
      preLoaderRoute: typeof ApiMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/initiate': {
      id: '/api/mpesa/initiate'
      path: '/api/mpesa/initiate'
      fullPath: '/api/mpesa/initiate'
      preLoaderRoute: typeof ApiMpesaInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/send': {
      id: '/api/newsletter/send'
      path: '/api/newsletter/send'
      fullPath: '/api/newsletter/send'
      preLoaderRoute: typeof ApiNewsletterSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/subscribe': {
      id: '/api/newsletter/subscribe'
      path: '/api/newsletter/subscribe'
      fullPath: '/api/newsletter/subscribe'
      preLoaderRoute: typeof ApiNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/digest': {
      id: '/api/notifications/digest'
      path: '/api/notifications/digest'
      fullPath: '/api/notifications/digest'
      preLoaderRoute: typeof ApiNotificationsDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/email': {
      id: '/api/notifications/email'
      path: '/api/notifications/email'
      fullPath: '/api/notifications/email'
      preLoaderRoute: typeof ApiNotificationsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/push-send': {
      id: '/api/notifications/push-send'
      path: '/api/notifications/push-send'
      fullPath: '/api/notifications/push-send'
      preLoaderRoute: typeof ApiNotificationsPushSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/push-subscribe': {
      id: '/api/notifications/push-subscribe'
      path: '/api/notifications/push-subscribe'
      fullPath: '/api/notifications/push-subscribe'
      preLoaderRoute: typeof ApiNotificationsPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/events': {
      id: '/api/settings/events'
      path: '/api/settings/events'
      fullPath: '/api/settings/events'
      preLoaderRoute: typeof ApiSettingsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor/threads': {
      id: '/api/tutor/threads'
      path: '/api/tutor/threads'
      fullPath: '/api/tutor/threads'
      preLoaderRoute: typeof ApiTutorThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutor/quizzes_/$quizId': {
      id: '/_authenticated/tutor/quizzes_/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/tutor/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedTutorQuizzesQuizIdRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
  }
}

interface AuthenticatedTutorRouteChildren {
  AuthenticatedTutorThreadIdRoute: typeof AuthenticatedTutorThreadIdRoute
  AuthenticatedTutorChatsRoute: typeof AuthenticatedTutorChatsRoute
  AuthenticatedTutorDocumentsRoute: typeof AuthenticatedTutorDocumentsRoute
  AuthenticatedTutorPlannerRoute: typeof AuthenticatedTutorPlannerRoute
  AuthenticatedTutorQuizzesRoute: typeof AuthenticatedTutorQuizzesRoute
  AuthenticatedTutorSavedRoute: typeof AuthenticatedTutorSavedRoute
  AuthenticatedTutorQuizzesQuizIdRoute: typeof AuthenticatedTutorQuizzesQuizIdRoute
}

const AuthenticatedTutorRouteChildren: AuthenticatedTutorRouteChildren = {
  AuthenticatedTutorThreadIdRoute: AuthenticatedTutorThreadIdRoute,
  AuthenticatedTutorChatsRoute: AuthenticatedTutorChatsRoute,
  AuthenticatedTutorDocumentsRoute: AuthenticatedTutorDocumentsRoute,
  AuthenticatedTutorPlannerRoute: AuthenticatedTutorPlannerRoute,
  AuthenticatedTutorQuizzesRoute: AuthenticatedTutorQuizzesRoute,
  AuthenticatedTutorSavedRoute: AuthenticatedTutorSavedRoute,
  AuthenticatedTutorQuizzesQuizIdRoute: AuthenticatedTutorQuizzesQuizIdRoute,
}

const AuthenticatedTutorRouteWithChildren =
  AuthenticatedTutorRoute._addFileChildren(AuthenticatedTutorRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedTeacherEscalationsRoute: typeof AuthenticatedTeacherEscalationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedTeacherEscalationsRoute: AuthenticatedTeacherEscalationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CallbackRoute: CallbackRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStreamTestRoute: ApiStreamTestRoute,
  ApiMpesaCallbackRoute: ApiMpesaCallbackRoute,
  ApiMpesaInitiateRoute: ApiMpesaInitiateRoute,
  ApiNewsletterSendRoute: ApiNewsletterSendRoute,
  ApiNewsletterSubscribeRoute: ApiNewsletterSubscribeRoute,
  ApiNotificationsDigestRoute: ApiNotificationsDigestRoute,
  ApiNotificationsEmailRoute: ApiNotificationsEmailRoute,
  ApiNotificationsPushSendRoute: ApiNotificationsPushSendRoute,
  ApiNotificationsPushSubscribeRoute: ApiNotificationsPushSubscribeRoute,
  ApiSettingsEventsRoute: ApiSettingsEventsRoute,
  ApiTutorThreadsRoute: ApiTutorThreadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
